### ISSUE TITLE
Support cocoa pods

### ISSUE THREAD

**Issue by MarcSteven** [maxvol/JSONLayout#1]
As we all know ,Cocoapods was so fashion ,so do you plan to support Cocoapods ???

**Comment by maxvol** [comment]
No, I did not use CocoaPods since iOS8 and not planning to because SPM (Swift Package Manager) is almost ready for iOS/macOS anyway (it allows to specify iOS/macOS build targets, and supports the most tools CocoaPods is used for) and will become the new standard, making CocoaPods obsolete.

**Comment by MarcSteven** [comment]
Oh that's  a pity ...
